### ISSUE TITLE
Assessment 3 data: @jensorsel

### ISSUE THREAD

**Issue by JensOrsel** [cmda-fe3/course-17-18#473]
[This](http://statline.cbs.nl/Statweb/publication/?DM=SLEN&PA=7052eng&D1=0-1,7,30-31,34,38,42,49,56,62-63,66,69-71,75,79,92&D2=0&D3=0&D4=0,10,20,30,40,50,60,(l-1)-l&LA=EN&HDR=G1,G2,G3&STB=T&VW=T) is the data that I want to use ([download link](http://statline.cbs.nl/Statweb/publication/?VW=D&DM=SLEN&PA=7052eng&D1=0-1,7,30-31,34,38,42,49,56,62-63,66,69-71,75,79,92&D2=0&D3=0&D4=0,10,20,30,40,50,60,(l-1)-l&HD=171010-1717&LA=EN&HDR=G1,G2,G3&STB=T)). I understand it isn't too dirty, I chose this dataset purposely. I wanted to make sure that cleaning it up would still pose enough of a challenge, but that it wouldn't take up 90% of the time I spend on this assessment.

I'm planning on making a bar chart, with the functionality to sort between the highest and lowest value of death cause first. I want to add the functionality to choose between years as well - similar to [this](http://nbremer.github.io/top2000/).

Next to the bar chart, I want to make another (probably a pie) chart that shows the percentages of death cause per year (also affected by year slider). 100% is the total death count.

Fingers crossed I can actually pull this off!

**Comment by wooorm** [comment]
Looks good, a bit simple though, with not a lot of different variables.

Do the charts interact in some way?

**Comment by JensOrsel** [comment]
I wanted to keep the 'initial proposal' not too easy (for me), but also not too difficult. Since I don't have too much knowledge about what we're going to have to do, I don't want to go all-in just yet. My plan was to go with what can be read above, if I struggle a lot I can probably just get it done in time, if it turns out to be really easy I'll definitely be adding extras (more interactivity, complexer data for example).

**Comment by JensOrsel** [comment]
Update during class: I want to use [this](http://statline.cbs.nl/Statweb/publication/?DM=SLEN&PA=37478ENG&D1=0-2,5,8,11,14,17,21,24&D2=1,3&D3=0-1,18,35,52,69,86,103,120,137,154,171,188,205,222,239,256,273,290,307&LA=EN&HDR=T&STB=G1,G2&VW=T) dataset. A dropdown box will have filters to pick between Schiphol Airport and Eindhoven Airport. I want to use a linechart, preferably where the lines represent trails left by airplanes. This linechart will show the ups and downs in the amount of cross-country and local flights. This will be one of the visualisations. Next to this visualisation will be a pie chart, that shows the ratio between cross-country and local flights. Hovering over the items in the pie chart will make them light up in the linechart. More to be added later.

**Comment by wooorm** [comment]
Cool!
