### ISSUE TITLE
Assessment 3 data: @dipsaus9

### ISSUE THREAD

**Issue by dipsaus9** [cmda-fe3/course-17-18#506]
I want to challenge myself for the final assessment. I dont know yet if it will be possible in the short amount of time but we will see. 

[KNMI Website](http://projects.knmi.nl/klimatologie/daggegevens/selectie.cgi)

With this data i want to create an map of the Netherlands with all the data based on location. Will be a challenging assesment. I already created a structure that can transfer the data of the KNMI, i only need to find a way to get these locations based on name. 
But that is a job for the next time

**Comment by wooorm** [comment]
OK!

Are you combining it with other data?

**Comment by wooorm** [comment]
@dipsaus9 Ping!

**Comment by dipsaus9** [comment]
@wooorm sorry I didn't see your message, I'll combine this data with a GeoJson to create a map of the world. I also found some other data to make it more global. 
[https://data.worldbank.org/indicator/SP.DYN.LE00.IN?end=2015&locations=DZ-VE-ZW-NL&name_desc=true&start=1960&type=shaded&view=map&year=2015](https://data.worldbank.org/indicator/SP.DYN.LE00.IN?end=2015&locations=DZ-VE-ZW-NL&name_desc=true&start=1960&type=shaded&view=map&year=2015)
With this data ill draw a map and add all life expectacy. I'll make it interactive by animating each year. You can also click on each country to see more details. This will also create an new chart where you can compare these stats. It will be a bit like the chart they displayed on the website.

**Comment by wooorm** [comment]
Awesome!
