### ISSUE TITLE
Assessment 3 data: @wesleyc94

### ISSUE THREAD

**Issue by wesleyc94** [cmda-fe3/course-17-18#508]
For Assessment 3 I would like to use this dataset I've found on the website of CBS, Centraal Bureau voor Statistiek (http://statline.cbs.nl/Statweb/). While I was searching on the web for a dataset I found this set and it made me very curious about the subjects and the information inside this dataset. 

The dataset is about motor vehicles and every type, age, and class has been registered. The data goes from 2010 to 2017 and could be filtered on many things. For example Passenger cars, motor vehicles, commercial cars, Bus and many more. Because I think it is too much information all at once i've thought about subjects interested me the most. These are Passenger Cars, Motorcycles and the class of a vehicle (Age: Less than 1 year - 10 years old for example.) I would like to combine this by the years of 2010 to 2017 so there should be ways to display the data in a chart on many ways.

To show an example of the dataset, the original dataset could be found here:
http://statline.cbs.nl/statweb/publication/?dm=slen&pa=82044eng&la=en
The link dataset I would like to use could be found here: 
http://statline.cbs.nl/Statweb/publication/?DM=SLEN&PA=82044eng&D1=1,12&D2=1-10&D3=0-9,13-17&LA=EN&HDR=T&STB=G1,G2&VW=T
Within the original dataset I've filtered on a few things: By changing the selection on the top right i've DEselected all Total road vehicles and commercial cars. The remaning options should be passengers cars, motor vehicles, All classes and the period of 2010 to 2017 in years.

Wesley

**Comment by wooorm** [comment]
Looks good!
