### ISSUE TITLE
Assessment 3 data: @DesleyAalderink

### ISSUE THREAD

**Issue by DesleyAalderink** [cmda-fe3/course-17-18#509]
I like money, so I want to do something with numbers. On the CBS website I found statistics about the total amount of money of Dutch households. 

The link is: http://statline.cbs.nl/statweb/publication/?vw=t&dm=slen&pa=7116eng&hd=080429-0913&la=en

My plan is to show the total amount of money when you get on the graph, but there are 3 checkboxes you can select. With these checkboxes you can add the deposit and withdrawels. I want this graph to go over the existing one, not like a stacked graph. I want it to go inside of the total amount of money, so the difference is more noticeable. It must also be possible to disable the total numbers, deposit and withdrawels. This must happen with a smooth animation.

**Comment by DesleyAalderink** [comment]
I'm always interested in murder mystery shows/movies/games, so I chose data that's about murder and death. The data will go from 2010 to 2016 with data about man and woman. It's also categorized in age groups. Link to the data:

https://opendata.cbs.nl/dataportaal#/CBS/nl/dataset/81453NED/table?graphtype=Table&ts=1507842849930

For now I'm thinking about a barchart where you can mark checkboxes to activate and deactivate charts or multiple piecharts with the same basic idea. I'm still thinking about something more creative, but I'm still tired from the lack of sleep I had yesterday.

If I think of something else, I will post it here.  I will go to sleep now.

**Comment by wooorm** [comment]
@DesleyAalderink Wait, which set are you planning on using?

**Comment by DesleyAalderink** [comment]
I thought the first one I posted had to few rows, so I found the murder one which had more rows.
Or is the first one allright? 

Either way, I want to use all the data from the set.

**Comment by wooorm** [comment]
too* :p

I like this murders! More interesting than savings I think, but it may still not be enough to visualise? Depends on what you]re going to do I guess!
