### ISSUE TITLE
Assessment 3 data: @Senmetsu

### ISSUE THREAD

**Issue by Senmetsu** [cmda-fe3/course-17-18#513]
## Datakeuze
[Dit](https://raw.githubusercontent.com/fivethirtyeight/data/master/bob-ross/elements-by-episode.csv) is de data die ik wil gebruiken. Het komt af van de [fivethirtyeight/data](fivethirtyeight/data). Met de data wil ik een bubbel chart maken waarbij je kan zien welke objecten bob ross heeft geschilderd. Door op verschillende objecten te klikken kun je zien hoeveel procent van al zijn afleveringen er geschilderd zijn.

**Comment by wooorm** [comment]
[3 paragraphs](https://github.com/cmda-fe3/course-17-18/blob/master/class-4.md#description-1)

**Comment by wooorm** [comment]
@Senmetsu Ping!

**Comment by wooorm** [comment]
@Senmetsu Ping!
