### ISSUE TITLE
Assessment 3 data: @jessiegouw

### ISSUE THREAD

**Issue by jessiegouw** [cmda-fe3/course-17-18#517]
I'm going to visualize the amount of social contact that people in the
Netherlands have with each other. My plan is to make an interactive abstract chart, if that doesn't 
work I will make an interactive bar chart. 💪🏼

Here is the link to the source.
[Sociale contacten en maatschappelijke participatie](https://opendata.cbs.nl/dataportaal/#/CBS/nl/dataset/82249NED/table?graphtype=Table&ts=1507833594229)

**Comment by wooorm** [comment]
@jessiegouw What’s an “interactive abstract chart”?

**Comment by wooorm** [comment]
@jessiegouw Ping!

**Comment by jessiegouw** [comment]
I'm having a "writers block" for developers, sorry for the late response. Forget the abstract chart, I'm now busy making bart chart where you can toggle the chart in different categories. 

For example, how many times people connected with their neighbours, how many times people connected with their family, how many times people connected with their friends etcetera.

Another thing I'm planning to add is a click function which shows the amount of people (in percent) per category.  

🙃

**Comment by wooorm** [comment]
Oh okay, well good luck?!
