### ISSUE TITLE
Assessment 3 data: @WReins

### ISSUE THREAD

**Issue by WReins** [cmda-fe3/course-17-18#520]
Since I'm a pretty big classic rock fan I just have to go with [FiveThirtyEight's classic rock dataset](https://github.com/fivethirtyeight/data/tree/master/classic-rock).

The story behind this dataset is to see which artists are labeled as 'classic rock artists' in comparison to other states. The full story can be read [here](https://fivethirtyeight.com/features/why-classic-rock-isnt-what-it-used-to-be/).

There are two csv files that contain a lot of info. Artist information, year of song release, places of radio stations, number of times a song has been played etc. I think it's an interesting challenge to create a chart where i can combine all this data with filter options. With each selected filter, the chart displays data in different way, like:
* Most played songs per region
* Comparing popularity of artist per region
* Where are the 70s more prominent in comparison to other decades.
* etc

**Comment by wooorm** [comment]
🤘 AWESOME! 🤘
