### ISSUE TITLE
Assessment 3 data: @LucasBerghoef

### ISSUE THREAD

**Issue by lucasberghoef** [cmda-fe3/course-17-18#521]
# Class 4: Source

For this assignment I had to find a suitable and interesting set of data to use in the third assessment.

### Upcoming festivals in Amsterdam

All festivals in Amsterdam and the surrounding area as definined by "Amsterdam Marketing. This file gets updated daily with the latest Festivals and only contains upcoming Festivals, not past ones. (My version was downloaded on October 11th 2017) Data from [`data.amsterdam.nl`][https://open.data.amsterdam.nl/Festivals.csv].

#### Download link

https://data.amsterdam.nl/#?dte=catalogus%2Fapi%2F3%2Faction%2Fpackage_show%3Fid%3Ddf29c7bd-f34f-4ee3-9b4d-71b3e6aed791&dtfs=T&dsf=groups::toerisme-cultuur:res_format::CSV&mpb=topografie&mpz=11&mpv=52.3731081:4.8932945

#### Format

Comma-separated values (CSV) with 169 rows and 25 columns:

*   `Trcid` — (ex. "04197e05-4fde-441f-a3bc-69f758e76202")
*   `Title` — Title of the festival in Dutch
*   `Shortdescription` — A short description of the festival in Dutch
*   `Longdescription` — A long description of the festival in Dutch
*   `Calendarsummary` — A summary of the date, year and time when the festival takes place in Dutch
*   `TitleEN` — Title of the festival in English
*   `ShortdescriptionEN` — A short description of the festival in English
*   `LongdescriptionEN` — A long description of the festival in English
*   `CalendarsummaryEN` — A summary of the date, year and time when the festival takes place in English
*   `Types` — ...
*   `Ids` — ID numbers (ex. "2.4.1")
*   `Locatienaam` — The name of the festival location
*   `City` — The name of the city the festival is held in
*   `Adres` — The adress of the festival
*   `Zipcode` — The Zip code of the festival
*   `Latitude` — The latitude of the festival location
*   `Longitude` — The longitude of the festival location
*   `Urls` — The link to the website of the festival
*   `Media` — Media (images) of the festival
*   `Thumbnail` — A thumbnail image of the festival
*   `Datepattern_startdate` — ...
*   `Datepattern_enddate` — ...
*   `Singledates` — Date & year of the festival (DD-MM-YYYY)
*   `Type1` — ...
*   `Lastupdated` — When the festival information was last updated

#### Example

```csv
"Trcid";"Title";"Shortdescription";"Longdescription";"Calendarsummary";"TitleEN";"ShortdescriptionEN";"LongdescriptionEN";"CalendarsummaryEN";"Types";"Ids";"Locatienaam";"City";"Adres";"Zipcode";"Latitude";"Longitude";"Urls";"Media";"Thumbnail";"Datepattern_startdate";"Datepattern_enddate";"Singledates";"Type1";"Lastupdated";
"04197e05-4fde-441f-a3bc-69f758e76202";"Nationale Tulpendag";"In Amsterdam wordt elk jaar in januari tijdens de Nationale Tulpendag de officiële aftrap gegeven voor het tulpenseizoen. Iedereen mag gratis op de Dam tulpen plukken in een speciaal aangelegde pluktuin. Kom naar de Dam op de opening van De Nationale Tulpendag.";"<h2>Gratis tulpen plukken </h2> Elk jaar zorgen ... je eigen tulpen plukt op de Dam!";"Za 20 januari 2018, Toelichting: Datum voor 2018 genoemd onder voorbehoud.";"National Tulip Day";"The Dutch tulip season officially ... Amsterdam?s Dam Square. ";"<h2>Tulips from Amsterdam<strong></strong></h2> Every year, an estimated ... information visit the <a target=&quot:_blank&quot:>National Tulip Day website</a>.";"Sa 20 January 2018, Explanation: Date for 2018 to be confirmed.";"";"2.4.1";"Dam";"AMSTERDAM";"Dam";"1012 JS";"52,3731270";"4,8900800";"";"https://media.iamsterdam.com/ndtrc/Images/20130116/e1fcfdcb-2293-4d2e-ae0d-82d24057b8fb.jpg,https://media.iamsterdam.com/ndtrc/Images/20130116/f19d613c-37ce-41cf-9490-a2eb0b46da2d.jpg,https://media.iamsterdam.com/ndtrc/Images/20130116/9ba9caa0-9230-4818-aee0-2e0d924cd8ad.jpg";"https://media.iamsterdam.com/ndtrc/Images/20130116/e1fcfdcb-2293-4d2e-ae0d-82d24057b8fb.jpg";"";"";"20-01-2018";"";"2017-01-23 14:10:03";
...
"82c132db-e13e-4a77-8f89-83ebe6131265";"Sidewalk Sale ? Non Fiction";"";"";"Do 26 oktober 2017 11:00 - 18:00 uur.";"Sidewalk Sale ? Non Fiction";"The American Book Center and other booksellers pitch up at De Hallen for a sale of English-language non-fiction works, on offer from ?5. Shoppers can also bring books of their own (as long as they?re undamaged) and donate them to BetterWorldBook.  ";"";"Th 26 October 2017 11:00 - 18:00 hour.";"";"2.4.6";"De Hallen Amsterdam";"AMSTERDAM";"Hannie Dankbaarpassage 33";"1053 RT";"52,3668620";"4,8688550";"";"https://media.ndtrc.nl/Images/82/82c132db-e13e-4a77-8f89-83ebe6131265/91049ead-6d3a-4bd3-8489-5eeecf3c97da.jpg";"https://media.ndtrc.nl/Images/82/82c132db-e13e-4a77-8f89-83ebe6131265/91049ead-6d3a-4bd3-8489-5eeecf3c97da.jpg";"";"";"26-10-2017";"";"2017-08-17 19:45:16";
```

## Why I chose this data & how it can be used to reach the goals of assessment 3

I wanted to pick a data set that is actually relevant to my life and surroundings. That's why I started looking on the site of data.amsterdam.nl. At first I saw a dataset for food & drink gastronomy establishments in and around Amsterdam, but that was an incredibly big dataset. That's why I continued looking for something simmilar and I found the dataset of Festivals in and around Amsterdam. This dataset consisted of 169 rows and 25 columns, so it was a bit less intimidating than the food & drinks one. And of course I love going to festivals, so this data is actually relevant to me.

This dataset can be used to create multiple visualisation because it contains topographic data which can be used to create a visualisation with a map. But also contains time data that can be used to sort the festivals in order of date in a timetable. These two visualisations can be combined so when the user clicks on a festival in the timetable it also highlights that festival on the map. There is even enough data to perhaphs supply the viewer with a short discription of the festival.

The festivals could be sorted in a couple of different ways allowing the data to be interactive for the user. It can be sorted alphabetically, on date, or perhaphs on the ID numbers of the festival (but I have yet to discover what those mean, exactly). If plotting the coordinates on a topoJSON map of Amsterdam turns out to be too hard, I could also use the ZIPcodes to define the different areas of the festivals to see which festivals appear in which districts.

## License

MIT © Lucas Berghoef

**Comment by Razpudding** [comment]
Great description and pretty nice dataset Lucas. I would suggest contacting the marketing team that provided this data. I think their contact details are listed on the page. For my own vis which uses data from this same team, I ended up guessing what those IDs meant by listing the titles along side the different IDs. This might give you a sense of their meaning but it would be best to get the info straight from the source.
Good luck!
