### ISSUE TITLE
Assessment 3 data: @mymphy

### ISSUE THREAD

**Issue by mymphy** [cmda-fe3/course-17-18#523]
The data that I would like to use fr my assessment 3 is ["Vakanties; kerncijfers"](http://statline.cbs.nl/Statweb/publication/?DM=SLNL&PA=70232NED&D1=74%2c76%2c78%2c80%2c82%2c84%2c86%2c88%2c90%2c92%2c94%2c96%2c98%2c100%2c102%2c104%2c106%2c108%2c110%2c112%2c114%2c116&D2=15-26&HDR=T&STB=G1&VW=T). You can find the download link [here](http://statline.cbs.nl/Statweb/publication/?DM=SLNL&PA=70232NED&D1=74,76,78,80,82,84,86,88,90,92,94,96,98,100,102,104,106,108,110,112,114,116&D2=15-26&HDR=T&STB=G1&VW=D) (The first link "Puntkomma gescheiden waarden (CSV)").

The data is about vacation and it shows had a lot of information. It has data about going on vacation from the yeah 2005 until 2016. But shows also the countries that people went to. I think that with this data I could make different kinds of graphs showing for example where the most people go to when they are on vacation but I could also show the increase / decrease of vacationers.

### How to reach assessment 3’s goals:
* I am looking forward to work on this project because I will get more time to work on it and challenge myself to go beyond the example charts.
* With this data from CBS I can relate the data to each other and so include more features to the charts.
* Everything that I made until now I understand. I still find it difficult to come up with a code out of my head, but I think this 4 weeks was too short for that. After all the important thing is that I understand what my code does (comment everything that is important) and know to make changes when needed.

**Comment by Razpudding** [comment]
The data you've linked to is already a summary of other data. It's not a lot of data and I think you have to question how much more valuable it would be to see this data in a chart as opposed to in this table already provided by the CBS.
If you think you can provide several chart of this data set that provide meaningful insights, I will allow you to continue, but it's up to you. 
In the next class (today) we'll make some sketches of potential visualizations that will hopefully help you decide.
You can close this issue yourself as it's up to you.

**Comment by mymphy** [comment]
So I looked at my previous data again and I made some changes. I am still going to work with this data, but I also selected more subjects to the data.
So the data now is:
* All data is from 2005 until 2016.
* Average time that people go on vacation per year.
* Where people go on vacation. (In the Netherlands and outside Netherlands)
* How people go on vacation, so the differs kind of transport they use.
* How many people spent on their vacations.

You can find the whole data [here](http://statline.cbs.nl/Statweb/publication/?DM=SLNL&PA=70232NED&D1=1,3-4,6,8,10,12,14,16,18,20,22,24,26,28,30,32,34,36,38,62,64,66,68,70,72-74,76,78,80,82,84,86,88,90,92,94,96,98,100,102,104,106,108,110,112,114,116,142,144,146,148,150,152-153&D2=15-26&HDR=T&STB=G1&VW=T)

With this data I want to make an interactive graph that shows the difference between the vacation token inside and outside the Netherlands. Then when you click in one of the sides you go to another graph. For example if you click on vacation outside the Netherlands you go to a map of the world and there it will show where the Netherlands people travel to. And when you choose inside the Netherlands you get a map of The Netherlands.

So this is how I brainstormed my idea. I hope I will be able to pull this out!

**Comment by Razpudding** [comment]
Nice! I definitely think this will be rich enough data. Good luck!
