### ISSUE TITLE
Assessment 3 data: @velomovies

### ISSUE THREAD

**Issue by velomovies** [cmda-fe3/course-17-18#524]
For assessment 3 I will use a dataset from CBS. This dataset is a csv file and I will use it to show it in two graphs. 

The data from the dataset is about the kilometers traveled by people (Something like **192 billion** kilometer each year in the Netherlands). The data shows only information about the Netherlands. It has data of all provinces and from 2010 till 2015. 

The data does not only show the total kilometers. It also shows exactly where the kilometers are from. It shows kilometers by car, bicycle, train, and walking for instance. This data can be greatly used for a extended data visalization.

My idea is to show a map of the Netherlands and with color show the different kilometers. When you click on the map it will show more information about a certain province. 

This is the link to the dataset: [`CBS`](http://statline.cbs.nl/Statweb/publication/?DM=SLNL&PA=83497ned&D1=0&D2=a&D3=0,5-16&D4=a&HDR=T,G3&STB=G1,G2&VW=T)

> I hope I can pull this off and I am curious how far I will come

**Comment by wooorm** [comment]
> This data can be greatly used for a

A what? 😛

> a map of Holland

Just North and South Holland? What about the rest of the Netherlands 😛

Looks awesome, good luck!

**Comment by velomovies** [comment]
Sorry about that! Updated the issue

**Comment by wooorm** [comment]
Thanks! Looks good!
