### ISSUE TITLE
Assessment 3 data: @tpulido

### ISSUE THREAD

**Issue by tpulido** [cmda-fe3/course-17-18#528]
For assessment 3 I will be using [the food prices dataset from CBS](http://statline.cbs.nl/Statweb/publication/?DM=SLEN&PA=80346ENG&D1=8-48&D2=15-16&LA=EN&STB=G1,T&VW=T).

I chose this dataset because I think it can be displayed in creative ways. 

With the use of interactive bubbles I want to show the difference in products and prices, also the change in prices over time. I want to see if I can dynamicly add images for the different kind of foods. The bubbles will differ in size, color and maybe saturation.

I hope to include sort and filter functionality in the form of a side menu control panel.

**Comment by wooorm** [comment]
Missed this, sorry! I’m not entirely sure how interesting this data set is, as it doesn’t have a lot of separate field. From what you’re saying, it sounds like your only planning on one chart?

**Comment by tpulido** [comment]
What if I use the different categories provided in this [dataset](http://statline.cbs.nl/Statweb/publication/?DM=SLEN&PA=80346ENG&D1=4-50&D2=15-16&LA=EN&STB=G1,T&VW=T).

I can make several charts that highlight the different categories and show the change in price over time.

**Comment by wooorm** [comment]
Alright! It’s still data with relatively few different points, and only 2 years of data, but good luck!
