### ISSUE TITLE
Assessment 3 data: @kyunwang

### ISSUE THREAD

**Issue by kyunwang** [cmda-fe3/course-17-18#529]
# Class 4 - Source
For Assesment 3 I have chosen the dataset from FiveThirtyEight about [police killing in us](https://github.com/fivethirtyeight/data/blob/master/police-killings/police_killings.csv)

## The data
The data format is CSV and has 34 columns and 467 rows. Not all of the columns will be relevant for me though.

Header | Description | Source
---|-----------|----
`name` | Name of deceased | Guardian
`age` | Age of deceased | Guardian
`gender` | Gender of deceased | Guardian
`raceethnicity` | Race/ethnicity of deceased | Guardian
`month` | Month of killing | Guardian
`day` | Day of incident | Guardian
`year` | Year of incident | Guardian
`streetaddress` | Address/intersection where incident occurred | Guardian
`city` | City where incident occurred | Guardian
`state` | State where incident occurred | Guardian
`latitude` | Latitude, geocoded from address | 
`longitude` | Longitude, geocoded from address | 
`state_fp` | State FIPS code | Census
`county_fp` | County FIPS code | Census
`tract_ce` | Tract ID code | Census
`geo_id` | Combined tract ID code | 
`county_id` | Combined county ID code | 
`namelsad` | Tract description | Census
`lawenforcementagency` | Agency involved in incident | Guardian
`cause` | Cause of death | Guardian
`armed` | How/whether deceased was armed | Guardian
`pop` | Tract population | Census
`share_white` | Share of pop that is non-Hispanic white | Census
`share_bloack` | Share of pop that is black (alone, not in combination) | Census
`share_hispanic` | Share of pop that is Hispanic/Latino (any race) | Census
`p_income` | Tract-level median personal income | Census
`h_income` | Tract-level median household income | Census
`county_income` | County-level median household income | Census
`comp_income` | `h_income` / `county_income` | Calculated from Census 
`county_bucket` | Household income, quintile within county | Calculated from Census
`nat_bucket` | Household income, quintile nationally | Calculated from Census
`pov` | Tract-level poverty rate (official) | Census
`urate` | Tract-level unemployment rate | Calculated from Census
`college` | Share of 25+ pop with BA or higher | Calculated from Census

## Why I chose this dataset and how it can be used to assessment 3's goals

The reason I chose this dataset is that such controversial subjects interest me. With this dataset, I would also like to get more insight into whether the subjects introduced in the news were correct or not. E.g. the conduct of white policemen against black people.

the dataset is very versatile as it contains many types of data:
- categorical
With this set, we can put data against each other and make comparisons for clarification.
- topographical
Which can be used to visualize a map. To indicate the location of happening.
- numerical
Can and will be used with the categorical data to make comparisons and indicate the amount.
- sequential(date)
Can be used to set a timeline to indicate a 'story'. Say when each person has been killed sequentially.

The data can be filtered by date which will affect the locations plotted on a map with the topographical data. The categorical and numerical data also function as filters and/or indicators.
With topoJSON or geoJSON I can plot the map of us as a starter and continue from there.

**Comment by Razpudding** [comment]
Sounds interesting! Go ahead!
