### ISSUE TITLE
Data assessment 3: @MauSNL

### ISSUE THREAD

**Issue by MauSNL** [cmda-fe3/course-17-18#530]
Ik wilde graag de data gaan gebruiken van Bob Ross van [FiveThirtyEight](https://github.com/fivethirtyeight/data/tree/master/bob-ross) 

Wat betreft visualisaties opties denk ik dat er veel mogelijkheden zijn. Zoals in de les al gebleken kan er een pie chart, line chart, relatie chart en nog meer van gemaakt worden. 

Een voorbeeld is bijvoorbeeld een bubbel chart met alle elementen in zijn schilderijen en dan als je op een bubbel clicked een radial chart te laten zien met daar dan elementen die vaak in combinatie zijn gebruikt. Op de hoover kan je dan ook nog laten zien welke afleveringen dit gebruikt wordt, voor als je wil kijken hoe hij bijvoorbeeld snowy mountains schildert. Alles bij elkaar denk ik dat er nog best wat opties zijn.

**Comment by Razpudding** [comment]
Is goed. Er gaan wel meer mensen met deze dataset aan de slag maar ik ga er van uit dat je een andere visualisativorm zal kiezen dan zij in welk geval er geen probleem is.
