### ISSUE TITLE
Assessment 3 data: @Nina92

### ISSUE THREAD

**Issue by Nina92** [cmda-fe3/course-17-18#531]
Voor A3 wil ik een dataset gebruiken over wereldwijde alcoholconsumptie in 2010. Deze dataset komt van fivethirtyeight en kan [hier](https://github.com/fivethirtyeight/data/blob/master/alcohol-consumption/drinks.csv) gedownload worden. Dit doe ik door op _Raw_ te klikken en de code te kopiëren en te plakken in een lege CSV file.

In de dataset is te zien hoeveel glazen bier, glazen wijn, shots sterke drank en totaal aantal liter pure alcohol er per persoon per land werd gedronken dat jaar.

Ik wil deze data visualiseren in een choropleth map van de wereld. Hierbij kan gefilterd worden op glazen bier, glazen wijn en shots sterke drank.

Daarbij wil ik een bar chart maken waarin te zien is hoeveel liter pure alcohol per persoon per land werd gedronken. Deze bar chart kan gesorteerd worden op alfabet (naam van land), oplopend (aantal liter alcohol) en aflopend (aantal liter alcohol).

**Maar er is meer**
Mocht dit nou allemaal lukken en ik heb tijd over, dan wil ik nog het een en ander toevoegen.

Zo heb ik nog een dataset gevonden over de totale populatie per land. Deze dataset komt van data.worldbank.org en kan [hier](https://data.worldbank.org/indicator/SP.POP.TOTL?page=1) gedownload worden door rechts op het gewenste bestandstype te klikken (in mijn geval CSV).

Door mijn huidige dataset te combineren met deze dataset, kan ik berekenen hoeveel er in totaal per land is gedronken dat jaar. Hiervoor moet ik wel eerst de dataset cleanen, in de dataset staan namelijk alle gegevens van 1960 t/m 2016 en ik heb alleen het jaar 2010 nodig.

Deze data zou ik willen laten zien in een dual scale bar chart, waarbij de linker y-as het aantal liter (of aantal glazen) alcohol aangeeft en de rechter y-as het aantal inwoners.

Los van deze andere dataset, zou ik ook toe willen voegen dat je in de choropleth map op een land kan klikken, en dat er dan een bar chart verschijnt met de data over dat specifieke land.

Wat ik ook nog zou kunnen doen, is het aantal glazen en shots omrekenen naar liters zodat de eenheid overal hetzelfde is (vooral handig in een grouped of stacked bar chart). fivethirtyeight heeft voor het omrekenen naar glazen/shots [deze bron](https://www.rethinkingdrinking.niaaa.nih.gov/How-much-is-too-much/what-counts-as-a-drink/whats-A-Standard-drink.aspx) gebruikt.

- 1 glas bier = 12 ounce =  ± 350 ml
- 1 glas wijn = 5 ounce =  ± 150 ml
- 1 shot sterke drank = 1,5 ounce =  ± 45 ml

Lang verhaal, en ik verwacht zeker niet dat dit allemaal gaat lukken in zo'n korte tijd, maar ik heb in ieder geval genoeg opties voor uitbreiding :)

**Comment by Razpudding** [comment]
Hoi nina; Klinkt als een goed plan. Dekd at vooral die chloropleth interessant is. Als alternatief zou je ook bij mouseOver op een land een piechart kunnen laten zien die weergeeft hoe de verdeling is in dat land (bijv meer wijn dan bier).

**Comment by Nina92** [comment]
Goede tip! Die choropleth is sowieso al een uitdaging, hoop dat het allemaal (op tijd) gaat lukken. Fingers crossed :)
