### ISSUE TITLE
Assessment 3 data: @niyorn

### ISSUE THREAD

**Issue by niyorn** [cmda-fe3/course-17-18#532]
Link to src: https://www.kaggle.com/miroslavsabo/young-people-survey
Download link: https://www.kaggle.com/miroslavsabo/young-people-survey/data

#Young People Survey
_Explore the preferences, interests, habits, opinions, and fears of young people_

This data contains:

- Demographics
- Spending habbits
- Personality traits
- Health habits
- Phobias
- Hobies and interest
- Movie Preference
- Music preference

## Example

Music | Slow songs or fast songs | Dance | Folk | Country | Classical music
-- | -- | -- | -- | -- | --
5 | 3 | 2 | 1 | 2 | 2
4 | 4 | 2 | 1 | 1 | 1
5 | 5 | 2 | 2 | 3 | 4
5 | 3 | 2 | 1 | 1 | 1
5 | 3 | 4 | 3 | 2 | 4
5 | 3 | 2 | 3 | 2 | 3
5 | 5 | 5 | 3 | 1 | 2
5 | 3 | 3 | 2 | 1 | 2
5 | 3 | 3 | 1 | 1 | 2
5 | 3 | 2 | 5 | 2 | 2
5 | 3 | 3 | 2 | 1 | 2
5 | 3 | 1 | 1 | 1 | 4
5 | 3 | 1 | 2 | 1 | 4
5 | 3 | 5 | 3 | 2 | 1

1 = disagree 5 = totally agree

##What are we going to achieve
This data contains alot of different kind of variable.
With this data we can make a graph that show if different subject have a connection with each other

###First idea
See if music correlate with movie. The people who like the same genre of music, do they also like the same genre of movie.

###Second idea
Does age correlate with music preference. If people gets older to they lean towards the same kind of music genre?

###Third idea
Do women like the same genre of music and do men like the same genre of music.

**We're going to create a graph that can anwers this graph and more importantly: create new questions :)**

**Comment by Razpudding** [comment]
Ok your post was a bit confusing but I think I understand what you're going to do. Sounds interesting. You haven't mentioned the chart type you're thinking of using so I cant say if it's a good idea or not but the data is good so Ill close this issue.
