### ISSUE TITLE
Assessment 3 data: @rvdpas

### ISSUE THREAD

**Issue by rvdpas** [cmda-fe3/course-17-18#533]
For assessment 3 I will be using asylem requests dataset from [CBS](http://statline.cbs.nl/Statweb/publication/?DM=SLNL&PA=83102ned&D1=0&D2=1-2&D3=0-11&D4=0-6,8,10-45&D5=50,67&HDR=T,G4&STB=G1,G2,G3&VW=T).

The data is a about the amount of asylum requests in the Netherlands over the period of 2014 - 2016.

I think this dataset is really relevant and I think it will show multiple interesting charts.

For instance: 
- The difference between the years
- The amount / difference between men and women.
- The country they came from

I want to create a toggle so, you can switch between charts and / or data.

**Comment by Razpudding** [comment]
I agree, it sounds pretty interesting. In the set you linked I only see 2015/2016 but maybe you found some more data. I think it's a good idea to think about how to visualize this many countries. Maybe it's a good idea to group some of the less numerous origins (like all asian countries for instance). I would also love it if you could include the age somehow.
