### ISSUE TITLE
Assessment 3 data: @dylanvanzanten

### ISSUE THREAD

**Issue by dylanvanzanten** [cmda-fe3/course-17-18#534]
I want to use [this dataset](https://github.com/fivethirtyeight/data/blob/master/airline-safety/airline-safety.csv). It is a dataset from [FiveThirthyEight](https://fivethirtyeight.com). It contains the data of airlines with incidents and fatal incident from 1985 to 1999 and 1999 to 2004. 

I want create a scatter chart and a line chart that visualizes this data. First I wanted to create a chart from a world map, but the data doesn't contain the countries from where the airlines are from (maybe I can search for them, but that takes a lot of time). The scatter chart can go deeper in the visualisations the amount of fatal incidents. The line chart can contain also the amount of fatal incidents, but just with a line.

I also want to filter per airline with checkboxes or just buttons to see a line or scatter better. I hope I can create this assessment very well. The last assessment I was really struggling with interaction, but cleaning the data I already achieved.

**Comment by Razpudding** [comment]
The data looks interesting. You havent done a lot to describe it though. for instance, what does the column "avail_seat_km_per_week" stand for?
Make sure to provide an apt description of the data in your readme.
