### ISSUE TITLE
Assessment 3 data: @vriesm060

### ISSUE THREAD

**Issue by vriesm060** [cmda-fe3/course-17-18#535]
The data I would like to use for Assessment 3 is about vehicle and traffic incidents in the U.S. 
I originally found a dataset, called [Bad Drivers](https://github.com/fivethirtyeight/data/tree/master/bad-drivers), on the fivethirtyeight Github page. After researching where this data came from, I found a more complex dataset of the same topic on the website of the [National Highway Traffic Safety Administration.](https://www-fars.nhtsa.dot.gov/States/StatesCrashesAndAllVictims.aspx) This dataset features a lot of data, which I believe is very interesting to combine into a visualisation. 

The type of data gives me the opportunity to create a more complex and exciting datavisualisation than the ones I've made for the previous assessments and is a great challenge for me. I think the combination of the amount of incidents, fatalities, maybe by age group, and the alcohol percentages of drivers form a nice visualisation. My idea is to show the data for every state individually and to show an overview in the form of a map. There is also a possibility to show the data from different years, but I'm not quite sure if it's easy to add this option, since the dataset is already very large. My idea is to first focus on the data of one year and try to add other years when I have some time left to spend on this assessment.

**Comment by Razpudding** [comment]
The data you've linked looks interesting and rich enough. I do wonder how you plan on mapping it to a map. Alternatively, you could show one visualization showing some interesting data about all states combined, and another vis where the user can select a state and see a more detailed chart of that state. Just an idea of course ^^
