### ISSUE TITLE
Assessment 3 data: @jajan20

### ISSUE THREAD

**Issue by jajan20** [cmda-fe3/course-17-18#537]
## Sources
For assessment 3 I want to use 3 different exported txt files from my WhatsApp history.
I want to visualize the periods I'm the most active, which person I get messages from the most and at what time of day I'm chatting the most.

### Goals
The main goals are visualizing data and learning d3.
My data has a lot of content which I can use to visualize charts.

By combining different exported chats I can use multiple visualisations and different interactive styles. Since this is something I haven't done before (large scale) I'll need to look for examples from which I can learn and use this for assessment3.

For privacy reasons I only attached the first 10 lines from one export.
[Data](https://www.dropbox.com/s/fs9xqdy8j6q30bd/Screenshot%202017-10-16%2013.57.53.png?dl=0)

**Comment by wooorm** [comment]
How are you going to visualise it? 🤔

**Comment by wooorm** [comment]
@jajan20 Ping!

**Comment by jajan20** [comment]
First I'd like to create a pie chart in which al the members are present. By loading the data from my WhatsApp exports I can calculate who is the most active. This is very basic, but later I'll compare this data to the time and days. So I can see in which situation someone is most active. 

Second I'd like to make a filter for most used words (ignoring "de" "het" and "een"). And want to make this interactive (not really sure how and in which way but yeah).

For now this is all I can think of, I'm sure along the way I'll find new cool things to add and will update accordingly.

**Comment by wooorm** [comment]
Awesome & interesting! Good luck!
