### ISSUE TITLE
Assessment 3 data: @LarsMarjew

### ISSUE THREAD

**Issue by LarsMarjew** [cmda-fe3/course-17-18#538]
For assessment 3 I will create a visualization with this data-set [Terrorism West EU](http://www.start.umd.edu/gtd/search/Results.aspx?chart=country&casualties_type=&casualties_max=&region=8)

You can actually find every terrorist attack documented since 1970! But I will narrow it down to west EU from 2013-2016, you can easily select many categories to download selections of the data. The data-set is very extensive and documented many details and even reasons of terrorist attacks. With these details it would be fun for the users to play and easily compare every single attack, as well as seeing a complete overview of all the attacks and which category it fits.

I will visualize the attacks in bubbles in one main section where you can sort on many parameters and hover the attacks for a tooltip with the date, deaths/wounded, country/city, the attackers + their reason and what kind of victims. On the side there is more information about the complete picture in stacked bars showing the volume of the different reasoning behind attacks and a pie chart showing the complete mass over every single reason combined.

**Comment by Razpudding** [comment]
Sounds interesting. Guess you didnt make it to the oral exam?
