### ISSUE TITLE
Assessment 3 data: @RyanNL1994

### ISSUE THREAD

**Issue by RyanNL1994** [cmda-fe3/course-17-18#539]
# **Aantal geboren kinderen**
De dataset die ik heb gevonden gaat over het aantal geboren kinderen.
Ik heb deze dataset gekozen omdat het mij wel interessant leek om door de jaren/provincies te vergelijken hoeveel levende kinderen er worden geboren. Ook met vergelijking tussen jongens meisjes en het gemiddeld kindertal per vrouw.
Onder deze onderwerp hangen nog een paar data variabelen die ik nodig ga hebben voor mijn visualisatie voor assessment 3 namelijk:

- De regio's (op provincie)

- De jaren 2010 - 2015 (_ik kon meerdere jaren inladen, maar heb ervoor gekozen om dit te verkleinen tot de meest recente cijfers en ben dus uitgekomen op 2010 tot 2015_)

- Totaal levend geboren kinderen

- Levend geboren jongens

- Levend geboren meisjes

- Gemiddeld kindertal per vrouw

Deze data heb ik van de CBS (Centraal Bureau voor de Statistiek) en kan ik als een CSV bestand downloaden.

Link naar de data: 
[http://statline.cbs.nl/Statweb/publication/?DM=SLNL&PA=37201&D1=0,2-3,6&D2=5-16&D3=22-26&HDR=T&STB=G1,G2&VW=T](url)

# Voorbeeld van de data
<img width="722" alt="schermafbeelding 2017-10-16 om 15 52 55" src="https://user-images.githubusercontent.com/23642099/31615520-1cc4e108-b28a-11e7-8e2d-c211f6977337.png">

# Wat wil ik maken / vergelijken
Van de data met variabelen die ik heb wil ik een bar of een line grafiek maken (wat mij het beste lijkt met de data die ik heb).
Hierin wil ik door middel van bijv. een interactieve filter visualisatie de vergelijkingen laten zien tussen de aantal geboren kinderen in jaren, provincie's, aantal geboren jongens tegenover meisjes en eventueel de gemiddelde kindertal per vrouw.

**Comment by Razpudding** [comment]
Volgens mij kan je met een barchart of linechart niet EN de aantallen geboren kinderen EN de provincie EN de verhouding levend geboren laten zien. Met een stacked barchart of andere aanpassingen kan dit wel. Ik hoop dat je gaat schetsen voor je aan de slag gaat om te testen of je concept wel werkt.
Als je idd deze drie data dimenties mapped vind ik het goed. Alleen totaal geboren kinderen per provincie bijv is niet genoeg.
