### ISSUE TITLE
Assessment 3 data: @duy-linh

### ISSUE THREAD

**Issue by duy-linh** [cmda-fe3/course-17-18#541]
**Number of graduates by province**

For assessment 3 I want to use the [data from CBS](http://statline.cbs.nl/Statweb/publication/?DM=SLNL&PA=70072NED&D1=107-110&D2=5-16&D3=10-22&HDR=T&STB=G1,G2&VW=T) about 
the number of graduates by province. The data can be downloaded as CSV format, in the left bar.

The data that's usable for me, is between the years of 2005 to 2014. There is no recent data about the number of graduates by province, but there is a dataset about the number of students by province, which contains recent data.

_What do I want to make?_
I want to use a map of the Netherlands, and show all the province on the map. When you're hovering on a province, a graph will appear and show the number of graduates. I guess it's similar to the tooltip. I also want to add a filer/sort option, still thinking about how to do so.

**Comment by Razpudding** [comment]
Als je de verhoudingen wilt laten zien binnen een provincie ok
