### ISSUE TITLE
Assessment 3 data: @zezavdh

### ISSUE THREAD

**Issue by zezavdh** [cmda-fe3/course-17-18#544]
For assessment 3 I am going to use The Most Common Unisex Names In America.

"" | "name" | "total" | "male_share" | "female_share" | "gap"
-- | -- | -- | -- | -- | --
"1" | "Casey" | 176544.328149,0.584286566204162 | 0.415713433795838 | 0.168573132408324
"2" | "Riley" | 154860.665173 | 0.507639071226889,0.492360928773111,0.0152781424537786
"3" | "Jessie" | 136381.830656 | 0.47783426831522 | 0.52216573168478 | 0.04433146336956
"4" | "Jackie" | 132928.78874 | 0.421132601798505 | 0.578867398201495 | 0.15773479640299
"5" | "Avery" | 121797.419516 | 0.335213073103216 | 0.664786926896784 | 0.329573853793568

### Why this data?
I can do a couple of things with this data: I can show how many people have a certain name, I can filter by gender and I can show the gap between the genders. I can also filter by name. 

### Ideas
I am going to visualize the data in a bar chart so I can show how many male, how many femal and the gap between the genders.

**Comment by Razpudding** [comment]
You haven't linked to the data source. Also: Is this all the data there is? Hardly worth visualizing as there are only 5 datapoints...
"a bar chart" Doesnt sound like multiple interactive visualizations. Is this the data you want to use for assessment 3?
I don't think there's enough here for you to work with tbh.
