### ISSUE TITLE
Assessment 3 data: @dorusth

### ISSUE THREAD

**Issue by dorusth** [cmda-fe3/course-17-18#545]
# Assessment 3 data

The data I chose is [Alcohol consumption in the world in 2010](https://github.com/fivethirtyeight/data/tree/master/alcohol-consumption)

## Why this data?
I chose this data because it seems like data that can be used in multiple visualisations to make the data clear and compare it per country.

## What I want to Make
I want to start of by visualising the overall alcohol consumption per country(maybe with the option to select per category of drink).
when a country is selected I want to show the consumption per category.

**Comment by Razpudding** [comment]
This is a very limited description of data and concept. You dont explain how you want to visualize per country, what chart type you want to use. I think you explained the concept better in class so I'm willing to let this slide but please note this data description wont be sufficient in your Readme!
