### ISSUE TITLE
Assessment 3 data: @Nickanthonygroen

### ISSUE THREAD

**Issue by Nickanthonygroen** [cmda-fe3/course-17-18#546]
# Assessment 3 data

I chose [the alcohol consumption in the world](https://github.com/fivethirtyeight/data/tree/master/alcohol-consumption)

# Why I chose

I chose this because I too like an alcoholic beverage from time to time. Also because it compares the amount of alcohol being consumed in categories, which I then can compare.

# What I want to Make

I want to make a list of the countries that drink the most, and then when you click on a country you can see what kind of alcohol gets consumed the most.

**Comment by wooorm** [comment]
Interesting! On a map?
