### ISSUE TITLE
Assessment 3 data: @yoeripasmans

### ISSUE THREAD

**Issue by yoeripasmans** [cmda-fe3/course-17-18#548]
As data source I would like to use the Europe terrorism fatalities in the EU by country. The source of the data is FiveThirtyEight. Found between the recommended data.

I would like to visualize the total fatalities in a map to give an overview. Then if the user clicks on the country they see a line graph, showing the fatalities by year. 

Link to data:
https://github.com/fivethirtyeight/data/blob/master/terrorism/eu_terrorism_fatalities_by_country.csv

**Comment by Razpudding** [comment]
Limited description of data and concept. I think I understand what you're making though so I'm willing to let this slide but you should describe the data a lot better in your readme!
